// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthHandler creates a new instance of MockAuthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthHandler {
	mock := &MockAuthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthHandler is an autogenerated mock type for the AuthHandler type
type MockAuthHandler struct {
	mock.Mock
}

type MockAuthHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthHandler) EXPECT() *MockAuthHandler_Expecter {
	return &MockAuthHandler_Expecter{mock: &_m.Mock}
}

// CreateAccount provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) CreateAccount(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockAuthHandler_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) CreateAccount(c interface{}) *MockAuthHandler_CreateAccount_Call {
	return &MockAuthHandler_CreateAccount_Call{Call: _e.mock.On("CreateAccount", c)}
}

func (_c *MockAuthHandler_CreateAccount_Call) Run(run func(c echo.Context)) *MockAuthHandler_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_CreateAccount_Call) Return(err error) *MockAuthHandler_CreateAccount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_CreateAccount_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) Login(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthHandler_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) Login(c interface{}) *MockAuthHandler_Login_Call {
	return &MockAuthHandler_Login_Call{Call: _e.mock.On("Login", c)}
}

func (_c *MockAuthHandler_Login_Call) Run(run func(c echo.Context)) *MockAuthHandler_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_Login_Call) Return(err error) *MockAuthHandler_Login_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_Login_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type MockAuthHandler
func (_mock *MockAuthHandler) Logout(c echo.Context) error {
	ret := _mock.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = returnFunc(c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthHandler_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthHandler_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockAuthHandler_Expecter) Logout(c interface{}) *MockAuthHandler_Logout_Call {
	return &MockAuthHandler_Logout_Call{Call: _e.mock.On("Logout", c)}
}

func (_c *MockAuthHandler_Logout_Call) Run(run func(c echo.Context)) *MockAuthHandler_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 echo.Context
		if args[0] != nil {
			arg0 = args[0].(echo.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthHandler_Logout_Call) Return(err error) *MockAuthHandler_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthHandler_Logout_Call) RunAndReturn(run func(c echo.Context) error) *MockAuthHandler_Logout_Call {
	_c.Call.Return(run)
	return _c
}
