// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/SergioLNeves/auth-session/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceRepository creates a new instance of MockDeviceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceRepository {
	mock := &MockDeviceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceRepository is an autogenerated mock type for the DeviceRepository type
type MockDeviceRepository struct {
	mock.Mock
}

type MockDeviceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceRepository) EXPECT() *MockDeviceRepository_Expecter {
	return &MockDeviceRepository_Expecter{mock: &_m.Mock}
}

// CreateDevice provides a mock function for the type MockDeviceRepository
func (_mock *MockDeviceRepository) CreateDevice(ctx context.Context, device *domain.Device) error {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for CreateDevice")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Device) error); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceRepository_CreateDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDevice'
type MockDeviceRepository_CreateDevice_Call struct {
	*mock.Call
}

// CreateDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - device *domain.Device
func (_e *MockDeviceRepository_Expecter) CreateDevice(ctx interface{}, device interface{}) *MockDeviceRepository_CreateDevice_Call {
	return &MockDeviceRepository_CreateDevice_Call{Call: _e.mock.On("CreateDevice", ctx, device)}
}

func (_c *MockDeviceRepository_CreateDevice_Call) Run(run func(ctx context.Context, device *domain.Device)) *MockDeviceRepository_CreateDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Device
		if args[1] != nil {
			arg1 = args[1].(*domain.Device)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceRepository_CreateDevice_Call) Return(err error) *MockDeviceRepository_CreateDevice_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceRepository_CreateDevice_Call) RunAndReturn(run func(ctx context.Context, device *domain.Device) error) *MockDeviceRepository_CreateDevice_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDeviceBySessionID provides a mock function for the type MockDeviceRepository
func (_mock *MockDeviceRepository) DeleteDeviceBySessionID(ctx context.Context, sessionID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeviceBySessionID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceRepository_DeleteDeviceBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDeviceBySessionID'
type MockDeviceRepository_DeleteDeviceBySessionID_Call struct {
	*mock.Call
}

// DeleteDeviceBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockDeviceRepository_Expecter) DeleteDeviceBySessionID(ctx interface{}, sessionID interface{}) *MockDeviceRepository_DeleteDeviceBySessionID_Call {
	return &MockDeviceRepository_DeleteDeviceBySessionID_Call{Call: _e.mock.On("DeleteDeviceBySessionID", ctx, sessionID)}
}

func (_c *MockDeviceRepository_DeleteDeviceBySessionID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockDeviceRepository_DeleteDeviceBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceRepository_DeleteDeviceBySessionID_Call) Return(err error) *MockDeviceRepository_DeleteDeviceBySessionID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceRepository_DeleteDeviceBySessionID_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) error) *MockDeviceRepository_DeleteDeviceBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDevicesByUserID provides a mock function for the type MockDeviceRepository
func (_mock *MockDeviceRepository) DeleteDevicesByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDevicesByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceRepository_DeleteDevicesByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDevicesByUserID'
type MockDeviceRepository_DeleteDevicesByUserID_Call struct {
	*mock.Call
}

// DeleteDevicesByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockDeviceRepository_Expecter) DeleteDevicesByUserID(ctx interface{}, userID interface{}) *MockDeviceRepository_DeleteDevicesByUserID_Call {
	return &MockDeviceRepository_DeleteDevicesByUserID_Call{Call: _e.mock.On("DeleteDevicesByUserID", ctx, userID)}
}

func (_c *MockDeviceRepository_DeleteDevicesByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockDeviceRepository_DeleteDevicesByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceRepository_DeleteDevicesByUserID_Call) Return(err error) *MockDeviceRepository_DeleteDevicesByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceRepository_DeleteDevicesByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *MockDeviceRepository_DeleteDevicesByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredDevices provides a mock function for the type MockDeviceRepository
func (_mock *MockDeviceRepository) DeleteExpiredDevices(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredDevices")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceRepository_DeleteExpiredDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredDevices'
type MockDeviceRepository_DeleteExpiredDevices_Call struct {
	*mock.Call
}

// DeleteExpiredDevices is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDeviceRepository_Expecter) DeleteExpiredDevices(ctx interface{}) *MockDeviceRepository_DeleteExpiredDevices_Call {
	return &MockDeviceRepository_DeleteExpiredDevices_Call{Call: _e.mock.On("DeleteExpiredDevices", ctx)}
}

func (_c *MockDeviceRepository_DeleteExpiredDevices_Call) Run(run func(ctx context.Context)) *MockDeviceRepository_DeleteExpiredDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceRepository_DeleteExpiredDevices_Call) Return(n int64, err error) *MockDeviceRepository_DeleteExpiredDevices_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockDeviceRepository_DeleteExpiredDevices_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockDeviceRepository_DeleteExpiredDevices_Call {
	_c.Call.Return(run)
	return _c
}

// FindDeviceBySessionID provides a mock function for the type MockDeviceRepository
func (_mock *MockDeviceRepository) FindDeviceBySessionID(ctx context.Context, sessionID uuid.UUID) (*domain.Device, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for FindDeviceBySessionID")
	}

	var r0 *domain.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Device, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Device); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceRepository_FindDeviceBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDeviceBySessionID'
type MockDeviceRepository_FindDeviceBySessionID_Call struct {
	*mock.Call
}

// FindDeviceBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockDeviceRepository_Expecter) FindDeviceBySessionID(ctx interface{}, sessionID interface{}) *MockDeviceRepository_FindDeviceBySessionID_Call {
	return &MockDeviceRepository_FindDeviceBySessionID_Call{Call: _e.mock.On("FindDeviceBySessionID", ctx, sessionID)}
}

func (_c *MockDeviceRepository_FindDeviceBySessionID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockDeviceRepository_FindDeviceBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceRepository_FindDeviceBySessionID_Call) Return(device *domain.Device, err error) *MockDeviceRepository_FindDeviceBySessionID_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceRepository_FindDeviceBySessionID_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) (*domain.Device, error)) *MockDeviceRepository_FindDeviceBySessionID_Call {
	_c.Call.Return(run)
	return _c
}
