// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// FindByEmail provides a mock function for the type MockQuerier
func (_mock *MockQuerier) FindByEmail(ctx context.Context, email string, dest any) error {
	ret := _mock.Called(ctx, email, dest)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, email, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockQuerier_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - dest any
func (_e *MockQuerier_Expecter) FindByEmail(ctx interface{}, email interface{}, dest interface{}) *MockQuerier_FindByEmail_Call {
	return &MockQuerier_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email, dest)}
}

func (_c *MockQuerier_FindByEmail_Call) Run(run func(ctx context.Context, email string, dest any)) *MockQuerier_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_FindByEmail_Call) Return(err error) *MockQuerier_FindByEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_FindByEmail_Call) RunAndReturn(run func(ctx context.Context, email string, dest any) error) *MockQuerier_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}
