// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	"github.com/SergioLNeves/auth-session/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) CreateSession(ctx context.Context, session *domain.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.Session
func (_e *MockSessionRepository_Expecter) CreateSession(ctx interface{}, session interface{}) *MockSessionRepository_CreateSession_Call {
	return &MockSessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session)}
}

func (_c *MockSessionRepository_CreateSession_Call) Run(run func(ctx context.Context, session *domain.Session)) *MockSessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Session
		if args[1] != nil {
			arg1 = args[1].(*domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) Return(err error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, session *domain.Session) error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeactivateSession(ctx context.Context, sessionID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_DeactivateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateSession'
type MockSessionRepository_DeactivateSession_Call struct {
	*mock.Call
}

// DeactivateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockSessionRepository_Expecter) DeactivateSession(ctx interface{}, sessionID interface{}) *MockSessionRepository_DeactivateSession_Call {
	return &MockSessionRepository_DeactivateSession_Call{Call: _e.mock.On("DeactivateSession", ctx, sessionID)}
}

func (_c *MockSessionRepository_DeactivateSession_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockSessionRepository_DeactivateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_DeactivateSession_Call) Return(err error) *MockSessionRepository_DeactivateSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_DeactivateSession_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) error) *MockSessionRepository_DeactivateSession_Call {
	_c.Call.Return(run)
	return _c
}

// FindSessionByID provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) FindSessionByID(ctx context.Context, sessionID uuid.UUID) (*domain.Session, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for FindSessionByID")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Session, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Session); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_FindSessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindSessionByID'
type MockSessionRepository_FindSessionByID_Call struct {
	*mock.Call
}

// FindSessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *MockSessionRepository_Expecter) FindSessionByID(ctx interface{}, sessionID interface{}) *MockSessionRepository_FindSessionByID_Call {
	return &MockSessionRepository_FindSessionByID_Call{Call: _e.mock.On("FindSessionByID", ctx, sessionID)}
}

func (_c *MockSessionRepository_FindSessionByID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *MockSessionRepository_FindSessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_FindSessionByID_Call) Return(session *domain.Session, err error) *MockSessionRepository_FindSessionByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_FindSessionByID_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) (*domain.Session, error)) *MockSessionRepository_FindSessionByID_Call {
	_c.Call.Return(run)
	return _c
}
